allprojects {
    repositories {
        maven {
            url "https://mvnrepository.com/artifact"
            mavenLocal()
        }
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/foreseecode/public-packages")
            credentials {
                // Please refer to the README.md for detailed instructions on generating your personal key.
                // README.md can be found in the root of repository.
                username = System.getenv("GITHUB_USERNAME")
                password = System.getenv("GITHUB_PERSONAL_KEY")
            }
        }
    }
}